name: Tests
on:
  push:
  pull_request:
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
      - name: Run gofmt
        run: gofmt -l .
      - name: Run go tests
        run: go test ./...

