name: Tests
on:
  push:
  pull_request:
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Run go fmt
        run: gofmt -l .
      - name: Run go vet
        run: go vet ./...
      - name: Run go cyclo
        run: gocyclo -over 15 .
      - name: Run go lint
        run: golint
      - name: Run ineffassign
        run: ineffassign ./*
      - name: Run go tests
        run: go test ./...

